"""
tools/browser_parity.py - SGT and SDIS reads of the same fictional pages in every browser (Part R.2)
===================================================================================================
Serves fictional pages on 127.0.0.1 (the two tests/class_diff_align clients, regenerated by
make_clients.py, and make_form.py's form with a dropdown, radio buttons, a checkbox and a password
box), opens each installed browser (Chrome, Edge, Firefox) ALONE with a throwaway profile, reads
each page the way SGT and SDIS do, closes only the processes it started, deletes the profile and
prints a parity table: address read, SGT lines (plus "Selected:" lines and the lines that differ
between browsers), whether the fictional password was ever read (must be NO), node counts, ms.

Client A is opened with client B as a second tab: SGT's lines must hold A's values only (a page
in a background tab is never read).

The reads of the two clients are saved as fixtures, tests/class_diff_align/client_{A,B}_<browser>.json,
in key_probe --once format with every 127.0.0.1 address replaced by test.local.

Never touches any window or process it did not start: windows are looked for only among the
started browser's own processes, and closing terminates that process tree by PID, never by name.
Opening the browsers takes focus for about half a minute per browser.

Usage:
    python tools/browser_parity.py                        # every installed browser
    python tools/browser_parity.py --browsers firefox     # only some (chrome, msedge, firefox)
    python tools/browser_parity.py --md docs/sdis/firefox-parity.md --no-fixtures
"""

import argparse
import json
import os
import re
import runpy
import shutil
import subprocess
import sys
import tempfile
import threading
import time
from collections import Counter
from datetime import datetime
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

ALIGN_DIR = os.path.join(ROOT, "tests", "class_diff_align")
PASSWORD = "Fictional#123"          # make_form.PASSWORD; no reader may ever return it
SELECTED_PREFIX = "Selected: "      # core.vsdc.vsdc_uia_text.SELECTED_PREFIX
WINDOW_TIMEOUT = 20.0
SETTLE_TIMEOUT = 10.0               # the first reads wake the accessibility tree up
READ_TIMEOUT = 10.0
LOCAL_RE = re.compile(r"127\.0\.0\.1(?::\d+)?")

_PF = os.environ.get("ProgramFiles", r"C:\Program Files")
_PF86 = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
BROWSERS = (
    ("chrome", os.path.join(_PF, "Google", "Chrome", "Application", "chrome.exe")),
    ("msedge", os.path.join(_PF86, "Microsoft", "Edge", "Application", "msedge.exe")),
    ("firefox", os.path.join(_PF, "Mozilla Firefox", "firefox.exe")),
)

# (page name, files opened as tabs - the first is the page read, title of the page read)
PAGES = (
    ("client_A", ("client_A.html", "client_B.html"), "SDIS align A"),
    ("client_B", ("client_B.html",), "SDIS align B"),
    ("form", ("form.html",), "SDIS parity form"),
)
FIXTURE_PAGES = ("client_A", "client_B")

# Firefox's first-run screens ("Welcome / Terms of Use") cover the page without these.
FIREFOX_PREFS = {
    "browser.aboutwelcome.enabled": False,
    "datareporting.policy.dataSubmissionPolicyBypassNotification": True,
    "browser.startup.homepage_override.mstone": "ignore",
    "startup.homepage_welcome_url": "",
    "browser.shell.checkDefaultBrowser": False,
    "toolkit.telemetry.reportingpolicy.firstRun": False,
    "trailhead.firstrun.didSeeAboutWelcome": True,
    "termsofuse.acceptedVersion": 999,
    # Measured 2026-10-04: the eight above still left the Terms of Use modal over the page.
    "termsofuse.acceptedDate": "1767225600000",
    "browser.preonboarding.enabled": False,
    "datareporting.policy.dataSubmissionPolicyAcceptedVersion": 999,
    "datareporting.policy.dataSubmissionPolicyNotifiedTime": "1767225600000",
    # A window behind others counts as occluded and its front page as offscreen: nothing is read.
    "widget.windows.window_occlusion_tracking.enabled": False,
}


def _say(msg: str) -> None:
    print(msg, flush=True)


# ---- pages and server ----------------------------------------------------------------------

def build_pages(folder: str) -> Dict[str, Any]:
    """Writes client_A/B.html (make_clients.py, run in `folder`) and form.html there. Returns
    make_clients' globals (CLIENTS: the fictional values)."""
    shutil.copy(os.path.join(ALIGN_DIR, "make_clients.py"), folder)
    sys.path.insert(0, ALIGN_DIR)
    try:
        import make_form
    finally:
        sys.path.remove(ALIGN_DIR)
    make_form.write(folder)
    return runpy.run_path(os.path.join(folder, "make_clients.py"))


def serve(folder: str):
    """http.server on 127.0.0.1 and a free port, in a thread. Returns (server, port)."""
    from functools import partial
    from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

    class Quiet(SimpleHTTPRequestHandler):
        def log_message(self, *args):
            pass

    server = ThreadingHTTPServer(("127.0.0.1", 0), partial(Quiet, directory=folder))
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, server.server_address[1]


def client_values(clients: Dict[str, Dict[str, Any]], name: str) -> set:
    """Every fictional value of one client, as text."""
    out: set = set()

    def add(v):
        if isinstance(v, str):
            out.add(v)
        elif isinstance(v, (list, tuple)):
            for x in v:
                add(x)
    for v in clients[name].values():
        add(v)
    return out


def foreign_lines(lines: List[str], foreign: Iterable[str]) -> List[str]:
    """The lines that are one of `foreign` (another client's own values). Whole lines, so a short
    value ("-") never matches inside a shared one ("GSTR-1")."""
    foreign = {f.strip() for f in foreign if f and f.strip()}
    return [ln for ln in lines if ln.strip() in foreign]


# ---- processes (only ever the ones started here) -------------------------------------------

def _process_table() -> Dict[int, Tuple[int, str]]:
    """{pid: (parent pid, exe name lower case)} of every process, via a Toolhelp snapshot."""
    import ctypes
    from ctypes import wintypes

    class PE32(ctypes.Structure):
        _fields_ = [("dwSize", wintypes.DWORD), ("cntUsage", wintypes.DWORD),
                    ("th32ProcessID", wintypes.DWORD), ("th32DefaultHeapID", ctypes.c_size_t),
                    ("th32ModuleID", wintypes.DWORD), ("cntThreads", wintypes.DWORD),
                    ("th32ParentProcessID", wintypes.DWORD), ("pcPriClassBase", ctypes.c_long),
                    ("dwFlags", wintypes.DWORD), ("szExeFile", ctypes.c_wchar * 260)]

    k32 = ctypes.windll.kernel32
    k32.CreateToolhelp32Snapshot.restype = wintypes.HANDLE
    snap = k32.CreateToolhelp32Snapshot(0x2, 0)          # TH32CS_SNAPPROCESS
    table: Dict[int, Tuple[int, str]] = {}
    entry = PE32()
    entry.dwSize = ctypes.sizeof(PE32)
    try:
        ok = k32.Process32FirstW(snap, ctypes.byref(entry))
        while ok:
            table[entry.th32ProcessID] = (entry.th32ParentProcessID, entry.szExeFile.lower())
            ok = k32.Process32NextW(snap, ctypes.byref(entry))
    finally:
        k32.CloseHandle(snap)
    return table


def _terminate(pid: int) -> bool:
    import ctypes
    k32 = ctypes.windll.kernel32
    h = k32.OpenProcess(0x0001, False, pid)              # PROCESS_TERMINATE
    if not h:
        return False
    try:
        return bool(k32.TerminateProcess(h, 1))
    finally:
        k32.CloseHandle(h)


def tree_pids(root: int, table: Dict[int, Tuple[int, str]], exe: str) -> List[int]:
    """root plus every descendant of it running the same exe (a browser's own processes)."""
    out, todo = [root], [root]
    while todo:
        parent = todo.pop()
        for pid, (ppid, name) in table.items():
            if ppid == parent and pid not in out and pid != parent and name == exe:
                out.append(pid)
                todo.append(pid)
    return out


def kill_tree(root: int, exe: str, table_fn: Callable[[], Dict[int, Tuple[int, str]]] = None,
              terminate: Callable[[int], bool] = None) -> List[int]:
    """Terminates the process tree started here (root's PID and its children), never by image
    name. Two passes: a child that was starting during the first is caught by the second (an
    orphan keeps its parent's PID). Returns the PIDs terminated."""
    table_fn = table_fn or _process_table
    terminate = terminate or _terminate
    exe = exe.lower()
    done: List[int] = []
    known = {root}
    for _ in range(2):
        table = table_fn()
        found: List[int] = []
        for start in sorted(known):
            for pid in tree_pids(start, table, exe):
                if pid not in found:
                    found.append(pid)
        for pid in found:
            known.add(pid)
            if pid in done or table.get(pid, (0, ""))[1] != exe:      # gone, or a reused PID
                continue
            terminate(pid)
            done.append(pid)
        time.sleep(0.3)
    return done


def launch_args(browser: str, exe: str, profile: str, urls: List[str]) -> List[str]:
    if browser == "firefox":
        return [exe, "-no-remote", "-profile", profile] + urls
    # Windows keeps a window started from a background process behind the others; Chromium then
    # counts the page as hidden and builds no accessibility tree (measured 2026-10-04: 0 lines, even
    # with --force-renderer-accessibility). These two make it treat the page as on screen.
    return [exe, f"--user-data-dir={profile}", "--no-first-run", "--no-default-browser-check",
            "--disable-features=CalculateNativeWinOcclusion", "--disable-backgrounding-occluded-windows",
            "--new-window"] + urls


def write_firefox_prefs(profile: str) -> None:
    with open(os.path.join(profile, "user.js"), "w", encoding="utf-8") as f:
        for k, v in FIREFOX_PREFS.items():
            f.write(f"user_pref({json.dumps(k)}, {json.dumps(v)});\n")


def find_window(pids: Iterable[int], title_part: str) -> int:
    """A visible top-level window of one of `pids` whose title contains title_part, or 0.
    Windows of any other process are skipped without reading their titles."""
    import ctypes
    from ctypes import wintypes
    user32 = ctypes.windll.user32
    pids = set(pids)
    hit = [0]

    @ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
    def _each(hwnd, _):
        pid = wintypes.DWORD()
        user32.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
        if pid.value not in pids or not user32.IsWindowVisible(hwnd):
            return True
        n = user32.GetWindowTextLengthW(hwnd)
        buf = ctypes.create_unicode_buffer(n + 1)
        user32.GetWindowTextW(hwnd, buf, n + 1)
        if title_part in buf.value:
            hit[0] = hwnd
            return False
        return True
    user32.EnumWindows(_each, 0)
    return hit[0]


# ---- one read --------------------------------------------------------------------------------

def _ms(fn: Callable[[], Any]) -> Tuple[Any, int]:
    t = time.perf_counter()
    out = fn()
    return out, int(round((time.perf_counter() - t) * 1000))


def read_window(hwnd: int, with_fixture: bool) -> Dict[str, Any]:
    """The address, SGT's lines, the node trees (control and raw) and, for a fixture, key_probe's
    raw read - each timed."""
    from core.sgt_i.uia_nodes import read_page_nodes
    from core.vsdc.vsdc_uia_text import read_page_text
    from tools.pre_dev.class_diff import key_probe

    deadline = time.monotonic() + SETTLE_TIMEOUT            # wait until two reads agree
    last = None
    while time.monotonic() < deadline:
        lines = read_page_text(hwnd, timeout_sec=READ_TIMEOUT, include_selection=True).get("lines") or []
        if lines and lines == last:
            break
        last = lines
        time.sleep(0.5)

    r: Dict[str, Any] = {"ms": {}}
    r["url"], r["ms"]["url"] = _ms(lambda: key_probe.read_url(hwnd))
    text, r["ms"]["lines"] = _ms(lambda: read_page_text(hwnd, timeout_sec=READ_TIMEOUT, include_selection=True))
    r["lines"] = text.get("lines") or []
    control, r["ms"]["control"] = _ms(lambda: read_page_nodes(hwnd, READ_TIMEOUT, raw_view=False))
    raw, r["ms"]["raw"] = _ms(lambda: read_page_nodes(hwnd, READ_TIMEOUT, raw_view=True))
    r["nodes_control"] = sum(len(d) for d in control["docs"])
    r["nodes_raw"] = sum(len(d) for d in raw["docs"])
    r["docs_control"] = len(control["docs"])
    seen = json.dumps([r["url"], r["lines"], control, raw], ensure_ascii=False)
    if with_fixture:
        k_control = key_probe.read_keys(hwnd, False, READ_TIMEOUT)
        k_raw = key_probe.read_keys(hwnd, True, READ_TIMEOUT)
        r["fixture_docs"] = key_probe._typed(k_raw, {key_probe._identity(n) for d in k_control for n in d})
        seen += json.dumps([k_control, k_raw], ensure_ascii=False, default=str)
    r["password_seen"] = PASSWORD in seen
    return r


def fixture_record(title: str, url: str, browser: str, docs: List[List[Dict[str, Any]]]) -> Dict[str, Any]:
    """key_probe --once format, every 127.0.0.1 address as test.local."""
    from core.sdis.keys import page_link
    record = {"title": title, "page": page_link(url) if url else "",
              "read_at": datetime.now().isoformat(timespec="seconds"), "docs": docs, "browser": browser}
    return json.loads(LOCAL_RE.sub("test.local", json.dumps(record, ensure_ascii=False)))


def run_browser(browser: str, exe: str, port: int, clients: Dict[str, Any],
                fixtures: bool, show_lines: bool = False) -> Dict[str, Dict[str, Any]]:
    """Every page in one browser, each in its own launch with a fresh throwaway profile."""
    results: Dict[str, Dict[str, Any]] = {}
    exe_name = os.path.basename(exe).lower()
    for page, files, title in PAGES:
        urls = [f"http://127.0.0.1:{port}/{f}" for f in files]
        profile = tempfile.mkdtemp(prefix=f"sdis_parity_{browser}_")
        if browser == "firefox":
            write_firefox_prefs(profile)
        proc = subprocess.Popen(launch_args(browser, exe, profile, urls))
        r: Dict[str, Any] = {"window": False}
        try:
            hwnd, deadline = 0, time.monotonic() + WINDOW_TIMEOUT
            while not hwnd and time.monotonic() < deadline:
                time.sleep(0.5)
                hwnd = find_window(tree_pids(proc.pid, _process_table(), exe_name), title)
            if hwnd:
                r = read_window(hwnd, fixtures and page in FIXTURE_PAGES)
                r["window"] = True
                if page == "client_A":
                    r["foreign"] = foreign_lines(r["lines"], client_values(clients, "B") - client_values(clients, "A"))
        finally:
            killed = kill_tree(proc.pid, exe_name)
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                pass
            for _ in range(10):
                shutil.rmtree(profile, ignore_errors=True)
                if not os.path.exists(profile):
                    break
                time.sleep(0.5)
        r["killed"] = len(killed)
        r["profile_left"] = os.path.exists(profile)
        if fixtures and r.get("fixture_docs"):
            path = os.path.join(ALIGN_DIR, f"{page}_{browser}.json")
            with open(path, "w", encoding="utf-8") as f:
                json.dump(fixture_record(title, r["url"], browser, r.pop("fixture_docs")), f,
                          ensure_ascii=False, indent=1)
            r["fixture"] = os.path.relpath(path, ROOT)
        results[page] = r
        _say(f"  {browser} {page}: window {'yes' if r['window'] else 'NO'}, {len(r.get('lines', []))} lines, "
             f"{r['killed']} processes closed")
        if show_lines:                  # fictional pages only, so printing them is allowed
            for ln in [f"URL: {r.get('url', '')}"] + r.get("lines", []):
                _say(f"      {ln}")
    return results


# ---- table (pure) --------------------------------------------------------------------------

def line_diff(lines_by_browser: Dict[str, List[str]]) -> List[Tuple[str, Dict[str, int]]]:
    """The lines not read the same number of times by every browser: (line, {browser: count}),
    in first-seen order."""
    counts = {b: Counter(lines) for b, lines in lines_by_browser.items()}
    order: List[str] = []
    for lines in lines_by_browser.values():
        for ln in lines:
            if ln not in order:
                order.append(ln)
    out = []
    for ln in order:
        per = {b: c[ln] for b, c in counts.items()}
        if len(set(per.values())) > 1:
            out.append((ln, per))
    return out


def same_order(lines_by_browser: Dict[str, List[str]]) -> bool:
    """Whether the lines every browser read come in the same order everywhere."""
    if not lines_by_browser:
        return True
    common = set.intersection(*(set(v) for v in lines_by_browser.values()))
    seqs = [[ln for ln in v if ln in common] for v in lines_by_browser.values()]
    deduped = [list(dict.fromkeys(s)) for s in seqs]
    return all(s == deduped[0] for s in deduped)


def selected_lines(lines: List[str]) -> List[str]:
    return [ln for ln in lines if ln.startswith(SELECTED_PREFIX)]


def parity_table(results: Dict[str, Dict[str, Dict[str, Any]]]) -> List[str]:
    """Markdown: per page one row per browser, then the lines that differ and the Selected: lines.
    results = {browser: {page: read}}."""
    out: List[str] = []
    browsers = list(results)
    pages = [p for p, _, _ in PAGES if any(p in results[b] for b in browsers)]
    for page in pages:
        out += [f"### {page}", "",
                "| browser | window | URL read | SGT lines | Selected: | password read | other client's lines "
                "| nodes control (documents) | nodes raw | ms url / lines / control / raw |",
                "| :--- | :--- | :--- | ---: | ---: | :--- | :--- | ---: | ---: | :--- |"]
        lines_by: Dict[str, List[str]] = {}
        for b in browsers:
            r = results[b].get(page)
            if not r:
                continue
            if not r.get("window"):
                out.append(f"| {b} | NO | | | | | | | | |")
                continue
            lines_by[b] = r["lines"]
            ms = r["ms"]
            foreign = "" if "foreign" not in r else str(len(r["foreign"]))
            out.append(f"| {b} | yes | {'yes' if r['url'] else 'NO'} | {len(r['lines'])} "
                       f"| {len(selected_lines(r['lines']))} | {'YES' if r['password_seen'] else 'no'} | {foreign} "
                       f"| {r['nodes_control']} ({r['docs_control']}) | {r['nodes_raw']} "
                       f"| {ms['url']} / {ms['lines']} / {ms['control']} / {ms['raw']} |")
        out.append("")
        if len(lines_by) > 1:
            diff = line_diff(lines_by)
            out.append(f"Lines that differ between browsers: {len(diff) or 'none'}; "
                       f"common lines in the same order: {'yes' if same_order(lines_by) else 'NO'}")
            if diff:
                out += ["", "| line | " + " | ".join(lines_by) + " |",
                        "| :--- | " + " | ".join("---:" for _ in lines_by) + " |"]
                out += [f"| `{ln}` | " + " | ".join(str(per[b]) for b in lines_by) + " |" for ln, per in diff]
            out.append("")
        for b, lines in lines_by.items():
            sel = selected_lines(lines)
            out.append(f"- {b} Selected: lines: " + ("; ".join(f"`{s}`" for s in sel) if sel else "(none)"))
        for b in lines_by:
            if results[b][page].get("foreign"):
                out.append(f"- {b}: lines of the background tab's client: "
                           + "; ".join(f"`{s}`" for s in results[b][page]["foreign"]))
        out.append("")
    return out


# ---- main ------------------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="SGT/SDIS reads of fictional pages in every browser.")
    ap.add_argument("--browsers", default="", help="comma list of chrome, msedge, firefox (default: all installed)")
    ap.add_argument("--md", default="", help="also write the table to this Markdown file")
    ap.add_argument("--no-fixtures", action="store_true", help="do not write the client_*_<browser>.json fixtures")
    ap.add_argument("--show-lines", action="store_true", help="print every page's address and SGT lines")
    args = ap.parse_args(argv)

    wanted = {b.strip() for b in args.browsers.split(",") if b.strip()}
    found = [(b, exe) for b, exe in BROWSERS if (not wanted or b in wanted) and os.path.isfile(exe)]
    for b, exe in BROWSERS:
        if (not wanted or b in wanted) and not os.path.isfile(exe):
            _say(f"{b}: not installed ({exe}) - skipped")
    if not found:
        _say("No browser to test.")
        return 1

    folder = tempfile.mkdtemp(prefix="sdis_parity_pages_")
    server = None
    try:
        clients = build_pages(folder)["CLIENTS"]
        server, port = serve(folder)
        _say(f"Serving fictional pages on 127.0.0.1:{port}")
        results = {b: run_browser(b, exe, port, clients, not args.no_fixtures, args.show_lines)
                   for b, exe in found}
    finally:
        if server:
            server.shutdown()
        shutil.rmtree(folder, ignore_errors=True)

    table = parity_table(results)
    _say("")
    for line in table:
        _say(line)
    if args.md:
        with open(args.md, "w", encoding="utf-8") as f:
            f.write(f"# Browser parity (fictional pages)\n\nWritten by `tools/browser_parity.py` on "
                    f"{datetime.now():%Y-%m-%d %H:%M}. Every page and value here is fictional.\n\n"
                    + "\n".join(table) + "\n")
        _say(f"Written {args.md}")
    bad = any(r.get("password_seen") or r.get("profile_left") for res in results.values() for r in res.values())
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
