"""Writes sdis-plan.json (run once by hand when re-planning; the dispatcher only reads the JSON).

    ../APP/venv/Scripts/python.exe docs/sdis/make_plan.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
AUTOFILL = HERE.parent / "autofill_tweaks" / "autofill-tweaks-plan.json"

PY = "../APP/venv/Scripts/python.exe"
T = f"{PY} -m pytest -q -p no:cacheprovider"
SDIS_TESTS = "tests/test_sdis_memory.py tests/test_class_diff_align.py"
REG = f"{PY} tools/sdis_regress.py"
COMMON = (f" EVERY WP: run `{REG}` before you change anything and again at the end; put both summaries"
          " (counts only) in your hand-off note and explain every number that changed. Run the SDIS tests"
          f" (`{T} tests/test_sdis_*.py tests/test_class_diff_align.py`). Never copy, print or quote"
          " anything from ../APP/tools/pre_dev/class_diff/output/ (real client data) except counts.")


def wp(wp_id, phase, model, size, deps, what, focus, kind="auto"):
    return {"wp": wp_id, "phase": phase, "model": model, "kind": kind, "size": size, "deps": deps,
            "what": what, "focus": focus + ("" if kind == "review" else COMMON)}


WPS = [
    wp("W0-1", 0, "sonnet", "M", [], "Baseline: tests + the regression runner tools/sdis_regress.py",
       "Blueprint section 0, Part A.3, section 9. The pre-dev engine is in tools/pre_dev/class_diff/ (keys.py,"
       " align.py, link_map.py, memory.py, compare.py). STEP 1: run"
       f" `{T} {SDIS_TESTS}` and record the result (expect 14 passed). STEP 2: write tools/sdis_regress.py."
       " It must: (a) take `--captures DIR`, default = the folder ../APP/tools/pre_dev/class_diff/output"
       " resolved from the repo root (REPO.parent / 'APP' / 'tools/pre_dev/class_diff/output'); if that does"
       " not exist, print 'no captures' and exit 0; (b) BEFORE importing link_map, set"
       " os.environ['SDIS_DATA_DIR'] to the captures folder and set link_map.OUT_DIR to it (link_map reads"
       " its captures from OUT_DIR; the worktree's own output/ folder is empty and git-ignored);"
       " (c) print, per (session, page link) map from link_map.build_maps(): snapshots merged, text nodes,"
       " DOUBLE COUNT (text nodes whose (align.shape(e), text) occurs more often in the merged map than in"
       " the snapshot that showed it most), LOST (texts some snapshot showed that are in no entry's"
       " 'values'), MULTI (entries holding more than one value); (d) per page link with 2+ clients"
       " (memory.client_maps()), build memory forward and in reversed client order (memory.build) and print"
       " each client's matched % and the verdict counts of memory.summary(), and 'orders agree: yes/no';"
       " (e) print total seconds. NEVER print a text or value, only counts, page links and session names."
       " Add `--save PATH` to also write the same printout to a file. STEP 3: run it and save it as"
       " docs/sdis/sdis-regress-baseline.txt (counts only, safe to commit). Expected today: double count 0"
       " and lost 0 on every map; services dashboard confirmed same/differs/composite 115/39/11; returns"
       " dashboard 90/6/7 plus 5 waiting; GSTR-1 92/13/18 plus 1 'changes within one client' and 4"
       " waiting; fictional GSTR-1 48/8 (+1 changes within one client) and GSTR-3B 55/8; orders agree yes"
       " everywhere. If your numbers differ, find out why before finishing and record it with `decide`."
       " STEP 4: tests/test_sdis_regress.py: copy tests/class_diff_align/client_A.json and client_B.json"
       " into tmp_path as key_probe_20260101_000000.json and key_probe_20260101_000100.json, run the"
       " runner's main(['--captures', str(tmp_path)]) and assert exit 0 and 'orders agree: yes' in the"
       " captured output (capsys)."),

    wp("W0-2", 0, "sonnet", "M", ["W0-1"], "Engine package core/sdis/ (pre-dev files become module aliases)",
       "Blueprint Part A.2 (the table and the alias rule are exact). STEP 1: create core/sdis/__init__.py"
       " (docstring: the pipeline capture -> merge (link_map) -> memory -> labels/relevance -> dialog, one"
       " line each) and core/sdis/paths.py with data_dir(): Path(os.environ['SDIS_DATA_DIR']) if set, else"
       " Path.home() / SERA_DATA_DIR_NAME / 'sdis' (import SERA_DATA_DIR_NAME from core.vsdc.vsdc_alerts,"
       " as core/sgt/sgt_corpus.py does), and write_csv() moved unchanged from tools/pre_dev/class_diff/"
       "compare.py. STEP 2: `git mv` tools/pre_dev/class_diff/keys.py, align.py, link_map.py, memory.py, tables.py"
       " into core/sdis/. Change their imports to absolute core.sdis ones (from core.sdis.align import"
       " align, pair_moved, shape ...). keys.LEARNED_FILE becomes data_dir() / 'learned_state.json';"
       " link_map.OUT_DIR and tables.OUT_DIR become data_dir(); tables._is_period imports is_period from"
       " core.sdis.labels (step 3) instead of compare. memory.py: `from compare import ...` is not allowed in core;"
       " see step 3. STEP 3: create core/sdis/labels.py and MOVE into it from compare.py, unchanged:"
       " FIXABLE_TYPES, SENTENCE_WORDS, the period regexes (_MONTH, _YEAR_PREFIX, _PERIOD_RES), is_period,"
       " value_type, element_type, _end, composites, CT_HYPERLINK/CT_IMAGE/CT_TABLE, NEVER_LABEL_CTYPES."
       " Create core/sdis/identity.py and MOVE into it from compare.py: CLIENT_FIELDS, _registry,"
       " client_ids, masked. compare.py imports all of them back (`from core.sdis.labels import ...`) so"
       " compare.compare_flat and every name the tests use still exist on the compare module. memory.py"
       " imports composites from core.sdis.labels, client_ids from core.sdis.identity, write_csv from"
       " core.sdis.paths. STEP 4: recreate tools/pre_dev/class_diff/keys.py, align.py, link_map.py,"
       " memory.py, tables.py as ALIASES, each exactly: a docstring naming the core module; `import os, sys`;"
       " `from pathlib import Path`; _HERE = Path(__file__).resolve().parent;"
       " os.environ.setdefault('SDIS_DATA_DIR', str(_HERE / 'output')); put _HERE.parents[2] on sys.path;"
       " `import core.sdis.<name> as _m`; then for link_map.py, memory.py and tables.py (they have main()):"
       " `if __name__ == '__main__': raise SystemExit(_m.main())` `else: sys.modules[__name__] = _m`;"
       " for keys.py and align.py just `sys.modules[__name__] = _m`. WHY: tests and compare.py set"
       " keys.VIEW and compare.ALIGN on the module; a star-import copy would silently not reach"
       " flatten(). STEP 5: tests/test_sdis_package.py: with tools/pre_dev/class_diff on sys.path,"
       " `import keys` is core.sdis.keys; setting keys.VIEW = 'sgt' changes core.sdis.keys.VIEW; core.sdis"
       " imports without PySide6; `import tables` is core.sdis.tables. tests/test_sdis_tables.py and"
       " tests/class_diff_tables/ stay as they are and must pass unchanged (capture_fixtures.py keeps"
       " importing the pre-dev key_probe, which does not move). STEP 6: switch tools/sdis_regress.py to import core.sdis directly (set"
       " SDIS_DATA_DIR first). The regression printout must be IDENTICAL to"
       " docs/sdis/sdis-regress-baseline.txt except the timing line; diff them and say so in the note."
       f" Prove the pre-dev scripts still import: `{PY} tools/pre_dev/class_diff/compare.py --help` and"
       f" `{PY} tools/pre_dev/class_diff/memory.py --help` and `{PY} tools/pre_dev/class_diff/tables.py --help`."),

    wp("W1-1", 1, "gemini_first", "S", ["W0-2"], "Part B: value history with times",
       "Blueprint Part B. In core/sdis/link_map.py LinkMap.add: each entry gets 'history', a list of"
       " [stamp, text]; append [stamp, text] when the element has text and it differs from the last"
       " history item's text (so a repeated text is stored once, a text that comes BACK after another is"
       " stored again). to_flat() adds 'history' to each item. In core/sdis/memory.py PageMemory._see: per"
       " client keep c['history'] (append the incoming items, skipping exact duplicates). Create"
       " core/sdis/history.py with day_of(stamp) -> 'YYYYMMDD': stamps look like '20261001_235545+0005.0'"
       " (capture snapshot), '20261001_235545' (single read) or an ISO time '2026-10-01T23:55:45' (the"
       " future recorder); take the first 8 digits after removing '-'; return '' if there are fewer."
       " Tests (tests/test_sdis_history.py): two snapshots with different texts -> 2 history items; the"
       " same text twice -> 1; A, B, A -> 3; day_of on all three formats; memory keeps each client's"
       " history apart. Nothing else changes: regression numbers identical."),

    wp("W1-2", 1, "gemini_first", "L", ["W0-2"], "Part G: screens (one link, several pages) by weighted matching",
       "Blueprint Part G (formulas are exact). STEP 1: core/sdis/screens.py: link_weights(sources) ->"
       " {(shape, text): weight} where sources are link_map.all_sources() tuples; links = number of"
       " distinct page links in sources; weight = math.log((1 + links) / links_showing_it); a key not in"
       " the dict (new text) gets math.log(1 + links); nodes without text weigh 0. covers(flat_new,"
       " flat_old, pairs, weights) -> (cover_new, cover_old) where pairs is {index in new: index in old};"
       " cover = matched weight / total weight on that side; if a side's total weight < 1e-9 its cover is"
       " 1.0 (a loading shell or an empty map never forces a new screen). same_screen(cover_new, cover_old)"
       " = max(...) >= SCREEN_MIN (0.5, a module constant). STEP 2: core/sdis/link_map.py build_maps: compute"
       " weights once from the sources; for each read, the candidate maps are the owner's maps of that link"
       " (keys (owner, link) for screen 1, (owner, f'{link} [screen {n}]') for n >= 2). For each candidate:"
       " cur = m.to_flat(); pairs = pair_moved(flat, cur, align(flat, cur, _always), _always); covers."
       " Add the read to the candidate with the best max(cover) if same_screen, else to a NEW screen map."
       " Give LinkMap two attributes: link (the base link) and screen (1, 2, ...). Let LinkMap.add accept"
       " an optional precomputed (flat, pairs) so the alignment is not done twice. STEP 3:"
       " core/sdis/memory.py client_maps(): group by base link; for each link keep a list of PageMemory"
       " (one per screen, attribute screen); assign each client's screen map to the PageMemory whose"
       " current order view gives the best max(cover) (same weights) if same_screen, else start a new"
       " PageMemory. build()/main()/regress runner treat each PageMemory as its own page, printed as"
       " 'link [screen n]'. STEP 4: tests/test_sdis_screens.py with the fixture client_A.json (helpers"
       " like tests/test_sdis_memory.py's _subtrees/_rebuild): (a) A then A plus one extra top-level block"
       " -> one screen; (b) a one-node shell with no text, then A -> one screen; (c) A, then a page that"
       " keeps only A's first and last top-level blocks and replaces the rest with new blocks of new text"
       " -> two screens; (d) covers() maths on a tiny hand-made example. Regression: no link splits on the"
       " real captures and every other number is unchanged; if a real link splits, stop, investigate and"
       " explain."),

    wp("W1-3", 1, "gemini_first", "L", ["W0-2"], "Part D: identity by session id + data fingerprint",
       "Blueprint Part D (thresholds exact). In the pre-dev captures a capture SESSION stands in for an"
       " SGT session. STEP 1: move group_clients and _by_time from core/sdis/link_map.py into"
       " core/sdis/identity.py (link_map re-exports them so old imports work). STEP 2: identity.py:"
       " fingerprint(map_a, map_b, rarity) -> (agree_weight, total_weight, n_values): pair the two maps'"
       " to_flat() with align+pair_moved (as memory._match does); keep only pairs where both texts are"
       " non-empty and labels.element_type(e) is NOT in labels.FIXABLE_TYPES and is not 'control'"
       " (data-shaped values only); weight of a value = 1 / rarity[(link, shape, text)], rarity = number of"
       " sessions whose map of that link shows that (shape, text); an equal pair adds its weight to agree"
       " and total; an unequal pair adds the mean of both weights to total. similarity = agree/total."
       " decide(sim, n): n >= MIN_VALUES (3) and sim >= SAME (0.9) -> 'same'; n >= 3 and sim <= DIFF (0.5)"
       " -> 'different'; else 'undecided'. resolve_owners(session_maps, session_ids) -> {session: owner}:"
       " start from group_clients(session_ids); for every session with NO ids, compare it with every other"
       " session sharing a page link (sum agree/total/n over the shared links): any 'same' -> take that"
       " session's owner (chain like group_clients, union-find); 'different' from every session it shares"
       " a link with -> its own client 'client <n>' (next free number); otherwise owner 'undecided"
       " <session>'. Sessions with ids keep their group_clients owner. STEP 3: memory.client_maps() uses"
       " resolve_owners and DROPS 'undecided ...' owners from memory (no vote); the regression runner"
       " prints owners per session. D4 is taken (user, 2026-10-04): NO VOTE - an undecided capture is dropped from memory and relevance."
       " STEP 4: tests/test_sdis_identity.py: fixtures A and B as two sessions with"
       " no ids -> 'different' -> two clients; A twice (two sessions) -> 'same' -> one client; a session"
       " with too few data values -> 'undecided'; chained ids still join. Regression: the two fictional"
       " sessions (no ids, same fictional page) become ONE client, so the fictional pages drop out of the"
       " memory section (one client); the two real GST clients stay two. Explain this in the note."),

    wp("W1-4", 1, "gemini_first", "M", ["W0-2"], "Part N: smart page link resolution",
       "Blueprint Part N. core/sdis/links.py: resolve(links_by_client: Dict[str, Set[str]]) ->"
       " Dict[str, str] mapping every link to its resolved link. A link is 'host/path#route' as"
       " keys.page_link() makes it. Split it into host + segments (path segments, then the route's"
       " segments after '#'). Group links by (host, number of segments, whether a route exists). Inside a"
       " group, look at every PAIR of links that differ in exactly ONE segment position i: if the two"
       " links belong to DIFFERENT clients (and not to a common client) that is one vote 'value at i'; if"
       " the same client has both, that is one vote 'page at i'. Position i is masked in that group when"
       " value votes >= 2 and page votes == 0: every link's segment i becomes '{v}'. Never mask the host,"
       " never mask a segment of letters only that the same client also visited with another value."
       " Links not in any masked group map to themselves. Do NOT use core/sgt_i atlas.url_hint. Wire it"
       " in: link_map.build_maps takes an optional link_of mapping (raw link -> resolved link) and keys maps"
       " by the resolved link; memory.client_maps computes the clients' raw links first (from the session"
       " maps it already builds), calls resolve(), then builds again with the mapping. Tests"
       " (tests/test_sdis_links.py): /returns/2026-27/summary for 3 clients -> one resolved link;"
       " /returns/gstr1 and /returns/gstr2b visited by the same client -> unchanged; a value position seen"
       " for only one client -> unchanged; a route segment ('#/auth/ARN123') resolved the same way."
       " Regression: no change expected on the real captures (their links carry no values); if one"
       " changes, explain."),

    wp("W1-5", 1, "gemini_first", "S", ["W0-2"], "Part M: per-browser memory",
       "Blueprint Part M. Every record may carry 'browser' (chrome / msedge / firefox / ''): the pre-dev"
       " captures have none, so they are browser ''. STEP 1: tools/pre_dev/class_diff/key_probe.py: when it"
       " saves a capture or read, add 'browser' = the window process's exe name without .exe, lower case"
       " (copy the OpenProcess / QueryFullProcessImageNameW approach of"
       " core/vsdc/vsdc_router.py get_foreground_info, for the hwnd key_probe already has). STEP 2:"
       " link_map.all_sources() passes the browser along (add it to the record dict it yields, key"
       " 'browser'); LinkMap gets attribute browser (from the first read). memory.client_maps() groups"
       " by (link, browser) - a PageMemory gets attribute browser - so pages are only compared with the"
       " same browser. The printout shows the browser when it is not ''. (Joining datapoints ACROSS"
       " browsers happens in W3-2.) Tests: two fixture reads of one link marked chrome and firefox ->"
       " two memories; both '' -> one. Regression unchanged."),

    wp("W1-6", 1, "opus", "M", ["W0-1"], "Part R.1: Firefox address bar, title, and never reading background tabs (SGT-C)",
       "Blueprint Part R (the measurements table is exact) and runner rule 6 (this touches SGT capture:"
       " Chrome and Edge must behave exactly as before). STEP 1: core/vsdc/vsdc_router.py, the address"
       " reader (around 'Look for Edit control (Address bar)'): today it searches ControlType 50004 (Edit)"
       " only. Search Edit OR ComboBox (50003) - build an OrCondition of the two ControlType conditions"
       " (uia.CreateOrCondition) - and keep the SAME name / automation-id keyword test and the same"
       " ValuePattern read and per-hwnd cache. Firefox's bar: ControlType 50003, AutomationId"
       " 'urlbar-input', Name 'Search with Google or enter address', Value = the full URL with scheme;"
       " 'url' in 'urlbar-input' already matches the keyword test. STEP 2: the same change in"
       " tools/pre_dev/class_diff/key_probe.py read_url (it searches 50004 only, around line 215). grep"
       " core/ and tools/ for any other place that finds the address bar by ControlType 50004 and fix it"
       " the same way (core/vsdc/vsdc_uia_text.py's UIA_EDIT_CONTROL_TYPE_ID is about page content, not"
       " the address bar: leave it). STEP 2b - BACKGROUND TABS (problem 25, the most important part of this WP: today SGT mixes a background tab's client into the client on screen in Firefox): core/vsdc/vsdc_uia_text.py _find_document_elements keeps only Documents whose CurrentIsOffscreen is false (read the property inside try/except; an element whose property cannot be read is kept, as today); core/sgt_i/uia_nodes.py read_page_nodes applies the same rule to the Documents it walks (grep how it finds them). Verified by hand on 2026-10-03 (blueprint Part R): client A in front, client B in a background tab -> today 227 lines with both clients, with the rule 52 lines of A only. Tests: fakes with two Documents, one offscreen -> only the onscreen one's lines/nodes; all Documents offscreen -> nothing; a Document whose IsOffscreen raises -> kept. STEP 3: the title cleanup in vsdc_router.py (the regex with 'mozilla"
       " firefox') and any other browser-suffix regex you find (grep -i 'google chrome' in core/): accept"
       " '-', '–' and '—' before the browser name (character class [-–—]). STEP 4: tests"
       " (tests/test_firefox_support.py) with fake UIA objects (follow the fakes in"
       " tests/test_vsdc_*uia*.py or tests/test_sgt_*.py - grep 'class Fake'): a window whose address bar"
       " is a ComboBox like Firefox's returns the URL; an Edit like Chrome's still returns it; a ComboBox"
       " whose name/id has no address keyword (a page dropdown) is NOT taken; titles '<page> — Mozilla"
       f" Firefox' and '<page> - Google Chrome' clean the same way. Run `{T} tests/test_sgt_*.py"
       f" tests/test_vsdc_*.py tests/test_firefox_support.py` and `{PY} tools/sgt_replay.py diff` (must show"
       " no change). Hands-on check: `check-add W1-6 --text \"Real GST and ITR sessions in Firefox: the"
       " HUD/SGT sees the portal (URL read) and captures the same fields as the same pages in Chrome\"`."),

    wp("W1-7", 1, "opus", "L", ["W1-6"], "Part R.2: browser parity tool + Firefox fixtures",
       "Blueprint Part R.2. STEP 1: D16 is taken (user, 2026-10-04): yes, you may open the browsers (throwaway profiles, fictional local"
       " pages only, close only the processes you started); no pop-up. STEP 2:"
       " tests/class_diff_align/make_form.py writes a fictional form page form.html (title 'SDIS parity"
       " form'): a dropdown with 3 options (2nd selected), 3 radio buttons (one checked), a ticked"
       " checkbox, a text box with a fictional value, a password box with the value 'Fictional#123', and a"
       " small table with a header row. STEP 3: tools/browser_parity.py: serve the folder"
       " tests/class_diff_align (client_A.html, client_B.html - regenerate them with make_clients.py into a"
       " temp folder if they are not committed - and form.html) with http.server on 127.0.0.1 and a free"
       " port, in a thread. For each browser found (Chrome: Program Files/Google/Chrome/Application/"
       "chrome.exe; Edge: Program Files (x86)/Microsoft/Edge/Application/msedge.exe; Firefox: Program"
       " Files/Mozilla Firefox/firefox.exe; skip the missing ones): make a temp profile folder and start it"
       " ALONE with that profile (Chrome/Edge: --user-data-dir=<tmp> --no-first-run"
       " --no-default-browser-check --new-window <url>; Firefox: -no-remote -profile <tmp> <url>, after writing a user.js into <tmp> that turns off the first-run screens - browser.aboutwelcome.enabled false, datareporting.policy.dataSubmissionPolicyBypassNotification true, browser.startup.homepage_override.mstone 'ignore', startup.homepage_welcome_url '', browser.shell.checkDefaultBrowser false, toolkit.telemetry.reportingpolicy.firstRun false, trailhead.firstrun.didSeeAboutWelcome true, termsofuse.acceptedVersion 999 - or Firefox's 'Welcome / Terms of Use' screen covers the page; ALSO open client_B as a second tab (pass both URLs) and check SGT's lines hold client A's values only), wait up"
       " to 20 s for a window whose title contains the page's title (EnumWindows), then read: the address"
       " (the W1-6 reader), SGT's lines (core.vsdc.vsdc_uia_text.read_page_text(hwnd,"
       " include_selection=True)), the node trees (core.sgt_i.uia_nodes.read_page_nodes control and"
       " raw_view=True), each timed. Then close it: terminate the process tree YOU started (by its PID and"
       " its children - never by image name: the user's own browsers run too) and delete the temp profile."
       " NEVER touch any other window. Print a parity table per page: URL read yes/no, number of SGT lines,"
       " lines that differ between browsers (these are fictional, so printing them is allowed), the"
       " 'Selected:' lines, whether 'Fictional#123' appears anywhere (must be NO), node counts, ms. STEP 4:"
       " save the raw reads as fixtures tests/class_diff_align/client_A_<browser>.json and"
       " client_B_<browser>.json in key_probe --once format ({title, page, read_at, docs}; docs from"
       " read_page_nodes raw view with the same node fields key_probe writes - reuse key_probe's"
       " typing/flag code rather than re-inventing it), with 'page' and every 127.0.0.1 address replaced"
       " by test.local as make_clients.py's docstring says. STEP 5: put the parity table (fictional, no"
       " client data) in docs/sdis/firefox-parity.md and summarise it in the hand-off note: every"
       " difference W2-5 must fix. If the answer was 'No', write the tool and its tests only, add a"
       " hands-on check 'run tools/browser_parity.py and commit its output', and finish. Tests"
       " (tests/test_browser_parity.py): the table/diff logic on hand-made line lists; the process"
       " cleanup only ever targets the PIDs it started (monkeypatch)."),

    wp("W1-8", 1, "opus", "M", ["W0-1"], "Part T: portal registration from service-settings login links",
       "Blueprint Part T, Part S.3 (portal_exceptions only) and rule 8. D21 is taken (user, 2026-10-04):"
       " the domain is shown and confirmed once on save, and a confirmed domain is in scope for BOTH SGT-C"
       " and the SDIS recorder. STEP 1: core/sdis/config.py, the loader for sdis_containers.json (blueprint"
       " S.3): load(paths) lays the office file (<Sera data dir>/sdis_containers.json) over the built-in"
       " core/sdis/sdis_containers.json (create it: version 1, empty levels, level_map, profile,"
       " containers, others, class_exceptions, portal_exceptions); check() refuses the whole file with a"
       " reason and the previous good version keeps running (follow how core/sgt/sgt_specs.py refuses a"
       " spec file and keeps the last good one). In this WP implement and check ONLY version and"
       " portal_exceptions; the other sections are read and passed through unchecked (W4-6 adds"
       " their checks). STEP 2: core/vsdc/vsdc_scope.py: registered_domain(host) = the host down to one"
       " label above its public suffix, from a module tuple PUBLIC_SUFFIXES (gov.in, nic.in, co.in,"
       " org.in, net.in, edu.in, ac.in, res.in, gen.in, firm.in, ind.in, com, org, net, in, io, gov);"
       " unknown suffix -> the full host; a bare suffix, _FORBIDDEN_ENTRIES, localhost or an IP -> None"
       " (an IP only when local test pages are allowed). service_domains(): {portal name: (domains,)}"
       " from the services table's login_page_link (read through the database the app already opened;"
       " never at import time; cached and cleared by reload_extra_domains()), minus never_register,"
       " plus portal_exceptions.extra_domains. is_in_scope_url and portal_for_url accept these domains"
       " exactly as they accept extra_domains() (parsed hostname, domain or subdomain). Income Tax and"
       " GST stay built in and win on overlap. STEP 3: core/sdis/portals.py: registered_portals() = the"
       " built-in two plus service_domains(), each {name, domains, source}; Part S's Others containers"
       " and every spec's portal use it. STEP 4: ui/dialogs/service_manager_dialog.py: on save, show the"
       " domain that will be watched and ask once (D21); a never_register domain or a link that gives no"
       " domain saves the service but registers nothing and says why. Deleting a service unregisters its"
       " domain (reload). STEP 5: the tripwire (core/vsdc/vsdc_router.py _tripwire_hosts, a portal title"
       " on an out-of-scope host) logs that host's registered domain so W4-5 can offer 'watch it too'"
       " (it becomes an extra_domains entry); no UI here. Tests (tests/test_sdis_portals.py):"
       " registered_domain for services.gst.gov.in, eportal.incometax.gov.in,"
       " unifiedportal-mem.epfindia.gov.in, www.mca.gov.in, a.b.example.co.in, gov.in (None),"
       " incometax.gov.in.evil.example (its own domain, never incometax), localhost (None); a service link"
       " puts its domain in scope and a lookalike host stays out; never_register refuses; extra_domains"
       " adds; removing the service takes it out; a broken config file is refused and the previous one"
       f" kept. Run `{T} tests/test_vsdc_scope*.py tests/test_sgt_*.py` and `{PY} tools/sgt_replay.py"
       " diff` with no services -> no change."),


    wp("W1-R", 1, "opus", "S", ["W1-1", "W1-2", "W1-3", "W1-4", "W1-5", "W1-6", "W1-7", "W1-8"], "Phase 1 review",
       "Review W1-1..W1-5 against blueprint section 0 and Parts B, D, G, M, N and their hand-off notes."
       " Check: the order in which link resolution (N), screens (G), browser (M) and identity (D) are"
       " applied in client_maps is consistent (resolve links -> identity -> per (link, browser) -> screens);"
       " no vote is ever counted per snapshot (R8); the regression numbers changed only where the notes"
       " explain it; the tests are meaningful. Fix defects with tests. Run the regression runner and all"
       " tests/test_sdis_*.py.", kind="review"),

    wp("W2-1", 2, "gemini_first", "L", ["W1-R"], "Part E: look-alikes scored, AMBIGUOUS",
       "Blueprint Part E. Implement in core/sdis/align.py exactly this (it was written once and passed all"
       " tests): AMBIGUOUS_MARGIN = 0.5; _MAX_CELLS = 40000. _pattern(text): collapse whitespace, digits ->"
       " '9', letters (regex [^\\W\\d_]) -> 'A', then collapse runs of the same char (re.sub(r'(.)\\1+',"
       " r'\\1', t)). _column(a, b): sideways overlap of node rects ([x, y, w, h], from e['node']['rect'])"
       " divided by the smaller width, 0.0 when a rect is missing or a width <= 0. _score(a, b) = (1.0 if"
       " _pattern equal else 0.0) + _column. _best_injection(score, banned=None): score is k rows x n"
       " columns (k <= n); DP dp[i][j] = max(dp[i][j-1], dp[i-1][j-1] + s) with s = -inf for the banned"
       " (row, col); every row must be paired, in order; return (total, chosen column per row); if the"
       " total is -inf return (-inf, []) WITHOUT backtracking. _look_alikes(xs, ys, fl, fp, pairs,"
       " ambiguous): rows = the shorter side; best = _best_injection(score); a row r is UNSURE when best -"
       " _best_injection(score, (r, chosen[r]))[0] < AMBIGUOUS_MARGIN; if k*n*k > _MAX_CELLS mark every row"
       " unsure without the extra runs; write the pairs (map back to fl/fp indexes when the shorter side"
       " was fp) and add the fl index to `ambiguous` when unsure and the fl element has text. In align():"
       " add parameter ambiguous: Optional[set] = None; inside each gap between anchors, group ga and gb by"
       " shape; shapes present on both sides with DIFFERENT counts are 'uneven'; pair the LCS-by-shape as"
       " today but skip pairs whose shape is uneven; then call _look_alikes for each uneven shape. Equal"
       " counts behave exactly as today. Wire-up: memory._match passes an ambiguous set; an observation"
       " paired ambiguously is stored with c['sure'] = False (a later sure observation of the same client"
       " sets it True); confirmed() counts only clients with sure True; verdict returns 'ambiguous' for a"
       " node whose clients include a not-sure one and that is not confirmed. compare.compare_flat passes"
       " a set too and sets check = 'ambiguous pairing - look-alikes, one side has fewer' for those rows."
       " link_map (same-client merge) does not pass a set. Tests (tests/test_sdis_lookalikes.py) on"
       " hand-made flats (dicts with key, text, node: {rect}): equal counts -> no ambiguous; 2 vs 1 with the"
       " single one matching the SECOND by pattern -> paired with the second, not ambiguous; 2 vs 1 with"
       " identical patterns and columns -> ambiguous; _pattern examples ('AB1234' -> 'A9', 'Filed' -> 'A')."
       " All 14 old tests must still pass and the merge numbers (double count, lost) must stay 0."),

    wp("W2-2", 2, "gemini_first", "M", ["W1-R"], "Part C: noise over time",
       "Blueprint Part C (rules in order). core/sdis/noise.py with functions on a PageMemory node:"
       " changes_within_client(node) (exists today in memory.verdict: any client with 2+ texts; move it"
       " here); changes_with_time(node): build {day: set of texts} from every client's history (day ="
       " history.day_of(stamp), the LAST text that client had on that day); true when there are 2+ days,"
       " every day's set has exactly one text, and the texts differ between days; probably_furniture(mem,"
       " nid): the node's verdict is 'differs between clients', labels.value_type(text) is 'sentence' or"
       " 'label', and it has NO label: until W3-1 brings real labels, 'no label' = none of the 6 nodes"
       " before it in mem.order is confirmed 'same for all clients' with a letter in its text"
       " (LABEL_LOOKBACK = 6; leave a TODO naming W3-1). memory.verdict order: retired (later), composite,"
       " 'changes within one client', 'changes with time', then the existing ones; 'probably furniture'"
       " replaces 'differs between clients' when it applies. D5 is taken (user, 2026-10-04): automatic, from SDIS's recorder (the code is the same either way)."
       " Tests (tests/test_sdis_noise.py) with hand-made"
       " PageMemory nodes: same text for 2 clients on day 1, another shared text on day 2 -> changes with"
       " time; different texts for 2 clients on the same day -> not; a long unlabelled sentence that"
       " differs -> probably furniture; the same with a label before it -> stays 'differs'. Regression:"
       " expect few or no changes (all captures are from one day); explain any."),

    wp("W2-3", 2, "gemini_first", "M", ["W2-1"], "Part F: the variable_alignment state",
       "Blueprint Part F. core/sdis/memory.py verdict: a node whose verdict would be 'same for all"
       " clients' becomes 'variable_alignment' when ALL of: labels.value_type(text) != 'label' (not ending"
       " in ':'), it is not composite, its ctype is not a choice control (keys.CHOICE_CTYPES), and at least"
       " one OTHER node with the same shape (align.shape) has the verdict 'differs between clients'"
       " (compute the set of 'differs' shapes once per call, not per node). In"
       " tools/pre_dev/class_diff/compare.py add VARIABLE_ALIGNMENT = 'variable_alignment' to STATUSES; in"
       " compare_flat, after statuses are set, a FIXED element whose shape is shared by a VARIABLE element"
       " (same exclusions) becomes VARIABLE_ALIGNMENT, and the label set ('shared') still includes it"
       " (row names like 'Cash ledger' must stay labels). Add a 'rejected' hook: memory accepts an optional"
       " set of rejected node signatures (link, shape, text) - a rejected one is plain 'same for all"
       " clients' again (W4-4 stores rejections). Tests: tests/test_class_diff_align.py must still pass"
       " unchanged (every value keeps its label); new tests: fixtures A/B give at least one"
       " variable_alignment (the 'Filed' status cells), and a rejected signature turns it back. Regression:"
       " print the variable_alignment count per page; explain the numbers."),

    wp("W2-4", 2, "gemini_first", "S", ["W1-R"], "Part H: memory upkeep (retire)",
       "Blueprint Part H (formula and worked examples exact). PageMemory keeps self.clients (the order"
       " clients were added); each node keeps first_ci (index of the client that created it) and last_ci"
       " (index of the last client that had it). After each add(): for every node in self.order that is"
       " confirmed: chances = len(self.clients) - first_ci; seen = number of clients that had it; misses ="
       " len(self.clients) - 1 - last_ci; p = (seen + 1) / (chances + 2); retire when misses >= 2 and"
       " (1 - p) ** misses < RETIRE_P (0.01): remove it from self.order, status 'retired', verdict"
       " 'retired'. Never retire an unconfirmed node. A retired node that a later client matches through"
       " pending simply comes back as a new pending node (nothing special). Tests"
       " (tests/test_sdis_retire.py): a node in 10 clients then missing in 4 -> retired; missing in 3 ->"
       " not; a node in 2 clients then missing in 4 -> not retired; an unconfirmed node never retires."
       " Regression unchanged (2 clients cannot retire anything); say so."),

    wp("W2-5", 2, "sonnet", "M", ["W1-R"], "Part R.3: Firefox line parity fixes (SGT-C)",
       "Blueprint Part R.3 and runner rule 6. Input: docs/sdis/firefox-parity.md and W1-7's hand-off note"
       " (the differences between Firefox's and Chrome's SGT lines on the fictional pages). If W1-7 found"
       " no difference, or could not run (no table), record that with `decide`, add nothing, and finish."
       " Otherwise fix each difference AS A KIND in core/vsdc/vsdc_uia_text.py (the line reader) or"
       " core/sgt_i/uia_nodes.py (node fields): e.g. a control type Firefox reports differently, a name"
       " Firefox puts in another property, a 'Selected:' line Firefox's dropdown/radio gives differently."
       " Never special-case a page or a text; when a rule must depend on the browser, key it on the"
       " element's framework id ('Gecko' vs 'Chrome'), not on a window title. Chrome and Edge lines must"
       f" not change: `{PY} tools/sgt_replay.py diff` shows no change and `{T} tests/test_sgt_*.py"
       " tests/test_vsdc_*.py tests/test_firefox_support.py` pass. Add a test per fixed difference using"
       " the Firefox fixtures from W1-7 (or fakes). If D16 was 'Yes', rerun tools/browser_parity.py and"
       " update docs/sdis/firefox-parity.md; else add a hands-on check to rerun it."),

    wp("W2-R", 2, "opus", "S", ["W2-1", "W2-2", "W2-3", "W2-4", "W2-5"], "Phase 2 review",
       "Review W2-1..W2-4 against section 0 and Parts C, E, F, H. Check the verdict order in memory is one"
       " clear function (retired, composite, noise, ambiguous, waiting, variable_alignment, probably"
       " furniture, same/differs) and is documented in its docstring; client order still changes no"
       " verdict (the runner's 'orders agree'); thresholds are module constants named as in D11. D11 is taken (user, 2026-10-04): keep the"
       " thresholds until the regression runner shows a reason. Fix defects with"
       " tests.", kind="review"),

    wp("W3-1", 3, "sonnet", "L", ["W2-R"], "Part I: statuses + labels from memory",
       "Blueprint Part I. For a node inside a real table (core.sdis.tables finds it: a cell's node index),"
       " its column label is tables.column_names(tb)[col] and, in a matrix (header_cols 1), its row label"
       " is that row's first cell; only when the node is in no table do the screen-box rules below apply."
       " Test it on tests/class_diff_tables fixtures (every body cell of t_ledger gets 'Tax / IGST'-style"
       " labels, t_matrix cells get both). STEP 1: move the label logic from tools/pre_dev/class_diff/compare.py into"
       " core/sdis/labels.py unchanged: _container, _children, _first_label, _same_column, _table_label,"
       " LABEL_LOOKBACK, _label (compare imports them back; tests/test_class_diff_align.py must pass"
       " unchanged). STEP 2: PageMemory keeps, per client, its last view: (flat, nid_of_idx) set in add()"
       " (index in that client's flat -> node id). STEP 3: memory.status(nid) maps verdicts to the"
       " dialog's statuses: 'same for all clients' + labels.FIXABLE_TYPES type -> fixed; 'same for all"
       " clients' + data type -> semi-variable; 'differs between clients' -> variable; variable_alignment;"
       " ambiguous; noise verdicts and probably furniture -> furniture; unconfirmed -> waiting; retired;"
       " composite. STEP 4: memory.label(nid): take the latest client view that holds the node, index i;"
       " the label candidates are the indexes whose node status is fixed or variable_alignment, or"
       " semi-variable with value_type 'alphanumeric' (as compare's 'shared'), minus composites, minus"
       " labels.NEVER_LABEL_CTYPES, and with a letter in the text; return labels._label(flat, i,"
       " candidates). Replace W2-2's temporary 'no label' check with label(nid) == ''. STEP 5:"
       " compare.py main(): the default now writes, per page memory, one CSV row per node with text:"
       " status, label, value type, clients, example value (latest client), key; the old two-client mode"
       " stays under --two. STEP 6: tests (tests/test_sdis_labels.py): build memory from fixtures A and B"
       " and check every value in tests/test_class_diff_align.py's EXPECTED gets its label from"
       " memory.label (import EXPECTED from that test module). Regression: print status counts per page."),

    wp("W3-2", 3, "gemini_first", "L", ["W3-1"], "Part J: relevance by occurrences + slots",
       "Blueprint Part J (counting rules exact). core/sdis/relevance.py: datapoints(memories, rejected=())"
       " -> list of Datapoint (dataclass: key, label, value_type, relevance_pct, sure_pct, pages: list of"
       " (link, screen, browser, share), nodes: list of (memory index, nid), slot_type_pct, surprise). A"
       " node counts when its status is variable or semi-variable (data, R2) - fixed, furniture,"
       " ambiguous, retired, composite and rejected variable_alignment do not. Its page share = clients"
       " that have it (sure observations) / clients in that PageMemory. Datapoints are JOINED across pages"
       " and browsers by key = (label lower-cased, trailing ':' and spaces removed, value type); a node"
       " with no label is its own datapoint keyed by (link, shape). relevance = sum of page shares;"
       " relevance_pct = round(100 * relevance / max relevance). sure_pct = round(100 * min(1, distinct"
       " clients / FULL_SURE_CLIENTS)) with FULL_SURE_CLIENTS from D3. Slots: the value types of all the"
       " datapoint's values -> slot_type_pct = share of the most common type; surprise = True when that"
       " share is >= 90% but some value has another type. D3 and D8 are taken (user, 2026-10-04): N = 2 to confirm, FULL_SURE_CLIENTS = 5; datapoints() takes picked"
       " keys and rejected keys (container moves count as rejections of the other containers): a"
       " picked key gets x1.5, a rejected key is left out. Print in memory.py main() and the regression runner: number of datapoints and the"
       " relevance_pct of the top 10 (numbers only, no labels). Tests (tests/test_sdis_relevance.py):"
       " fixed nodes never become datapoints; a value on 2 pages with the same label joins into one"
       " datapoint with 2 pages; a 50-row list counts once per client; share uses the page's own client"
       " count; slots and surprise."),

    wp("W3-4", 3, "gemini_first", "S", ["W3-1"], "Part R.4: SDIS on Firefox trees",
       "Blueprint Part R.4. If W1-7 saved Firefox fixtures (tests/class_diff_align/client_A_firefox.json"
       " and client_B_firefox.json): parametrize tests/test_class_diff_align.py and"
       " tests/test_sdis_labels.py over the browsers that have fixtures (the existing client_A/B.json are"
       " Edge reads; add chrome/firefox where present) so that, in every browser, alignment pairs 0"
       " template texts wrongly and every EXPECTED value gets its label. If a Firefox case fails, fix the"
       " KIND in core/sdis (keys.py, align.py, labels.py) - e.g. Firefox gives no grid column, so table"
       " labels must come from the screen-box fallback - never a Firefox-only special case unless keyed on"
       " a structural fact (framework id). Edge/Chrome results must not change. If there are no Firefox"
       " fixtures (D16 was 'No' and the user has not run the tool yet), record it with `decide`, add a"
       " hands-on check 'run tools/browser_parity.py, then rerun W3-4's tests', and finish."),

    wp("W3-5", 3, "gemini_first", "M", ["W3-2"], "Part S.1: class suggestion (what a value stays the same with)",
       "Blueprint Part S.1 (the table and thresholds are exact). core/sdis/classes.py:"
       " suggest(datapoints, memory_state) -> {datapoint key: ('profile' | 'dataset' | 'info' | None,"
       " reason)}. Per client (owners from Part D, undecided dropped), from the value history (Part B):"
       " PROFILE when the client's value is the same on every observation and the client has 2+"
       " observations on 2+ different days or periods; DATASET when it differs between the client's"
       " periods but is the same within each (client, period), with 2+ periods; INFO otherwise. The"
       " period of an observation = the period-shaped value (core.sdis.labels.is_period) shown ONCE on"
       " that snapshot, else the Part N masked link segment when is_period accepts it, else none (the"
       " observation is skipped for the dataset test). A class is suggested only when >= 90% of the"
       " clients with enough evidence give it (CLASS_AGREE = 0.9); otherwise None with the reason"
       " 'not enough evidence' or 'clients disagree'. Moves the user made (sdis_decisions kind"
       " 'container', read through the W3-2 picked/rejected inputs) override the suggestion. Datapoint"
       " gains suggested_class and class_reason. Print in the regression runner: counts per suggested"
       " class (numbers only). Tests (tests/test_sdis_classes.py, hand-made histories): one value per"
       " client over 3 days -> profile; per-period values constant within a period -> dataset; values"
       " changing within a period -> info; one observation -> None; 2 of 3 clients agreeing -> None."),

    wp("W3-3", 3, "sonnet", "L", ["W3-2"], "Part O engine: memory on disk, incremental mining",
       "Blueprint Part O (engine side only, no UI, no subprocess yet). STEP 1: core/sdis/store.py:"
       " save(state, path) / load(path) for the whole mining state as gzip JSON at data_dir() /"
       " 'memory.json.gz', written atomically (write a .tmp, then os.replace): every PageMemory (all its"
       " fields, as plain lists/dicts), the owners, the resolved-link mapping, the processed sources"
       " ({file name: [size, mtime]} plus per-file the stamps already taken), the rejected/picked keys and"
       " the time of the last run. A STATE_VERSION int; a different version means 'rebuild'. STEP 2:"
       " core/sdis/mine.py: mine(captures_dir, state_path=None, progress=None, cancel=None, rebuild=False)"
       " -> summary dict. It loads the state, lists the sources, takes only sources not yet processed,"
       " groups them into client maps the same way client_maps() does (links resolved over ALL links seen"
       " so far, identity over all sessions so far), and adds ONE client map at a time to the right"
       " PageMemory, calling progress(done, total, page_link) after each and saving the state after each"
       " (so Cancel loses at most one). cancel is a threading.Event-like object checked between clients."
       " A client already in a PageMemory that gets new pages is added again: votes are per client, so"
       " this is safe (PageMemory.add must not double-count it: test it). If the owners or link mapping"
       " of an ALREADY-ADDED session change, rebuild that page from scratch (log it). Then relevance is"
       " recomputed and stored. STEP 3: memory.py main() and the regression runner get --state to use"
       " mine(). Tests (tests/test_sdis_mine.py, tmp_path): mine twice -> the second run processes 0; add"
       " one capture -> processes 1; the verdict counts after incremental runs equal a fresh rebuild;"
       " cancel after the first client -> state saved with one client; a corrupt or old-version state ->"
       " rebuild. Regression: identical numbers through mine()."),

    wp("W4-1", 4, "opus", "L", ["W3-3"], "Part K: SDIS's own recorder (raw view, session id, browser)",
       "Blueprint Part K and rule 8 (this WP is the one place SGT is touched; SGT's own reads and results"
       " must not change). STEP 1: core/sdis/recorder.py SdisRecorder(directory=None, enabled=True,"
       " budget_s=1.5, cap_bytes=500*1024*1024, read_nodes=None, browser_of=None): offer(hwnd, session,"
       " portal, url, title) puts ONE pending job in a size-1 slot (a newer offer replaces an older one"
       " not yet taken) and returns at once - it must never block or raise. A daemon worker thread takes"
       " jobs: reads core.sgt_i.uia_nodes.read_page_nodes(hwnd, timeout_sec=budget_s, raw_view=True)"
       " (initialise COM on that thread the way core/sgt_i does for its own UIA thread - grep"
       " CoInitialize in core/sgt_i), measures the time, DROPS the record if it took longer than budget_s"
       " or came back empty, else appends one JSON line {v: 1, ts (ISO), session, portal, url, link"
       " (keys.page_link(url)), title, browser, docs} to sdis_YYYY-MM-DD.jsonl in directory (default:"
       " Path.home()/SERA_DATA_DIR_NAME/'sdis_capture' - NOT the admin corpus folder). browser_of(hwnd)"
       " = the window process exe name without .exe, lower case (same approach as"
       " core/vsdc/vsdc_router.py get_foreground_info). After each write, if the folder is bigger than"
       " cap_bytes, delete the oldest files until it is not (never the file being written). STEP 2:"
       " core/sgt/sgt_shadow.py: SgtShadow.__init__ gets sdis=None (keep it as self._sdis); in _observe,"
       " right AFTER the existing `if self._recorder is not None:` block (so after SGT's own read), add:"
       " `sdis = self._sdis` / `if sdis is not None and sdis.enabled: sdis.offer(hwnd, s.session_id,"
       " portal, url, title)` wrapped so nothing can raise. Nothing else in _observe changes. STEP 3:"
       " core/vsdc/vsdc_router.py builds SdisRecorder next to PageRecorder when the setting is on: new"
       " setting key 'sdis_record' (default '1'), a checkbox 'Record pages for Sera Distill (SDIS)' in"
       " ui/dialogs/unified_settings_dialog.py on the same page as 'Record pages for SGT testing'"
       " (grep it). STEP 4: core/sdis/sources.py: read_records(directory) yields the (stamp, session,"
       " link, rec) tuples link_map expects (stamp = ts, rec = {'docs': ..., 'browser': ...}); mine()"
       " accepts a recorder folder as well as pre-dev captures (detect by file name). D13 is taken (user, 2026-10-04): budget 1.5 s per changed page, 500 MB cap per staff PC. Tests"
       " (tests/test_sdis_recorder.py, fakes only, no real UIA): offer returns in < 5 ms with a reader that"
       " sleeps 2 s; a slow read is dropped; a fast one is written with every field; the size cap deletes"
       " the oldest file; a raising reader never escapes; SgtShadow with a stub sdis gets one offer per"
       " changed page and none when unchanged (follow tests/test_sgt_shadow*.py setups). Then run the SGT"
       f" tests (`{T} tests/test_sgt_*.py`) and `{PY} tools/sgt_replay.py diff` - it must show no"
       " change. Add a hands-on check: `check-add W4-1 --text \"Real Chrome, Edge and Firefox on a GST"
       " page: sdis_capture gets one record per changed page with the right browser; SGT capture behaves"
       " as before\"`."),

    wp("W4-2", 4, "opus", "L", ["W4-1"], "Part P: captures travel to the admin PC",
       "Blueprint Part P (protocol exact). D14 is taken (user, 2026-10-04): push over Sera Sync's transport, delete after the admin's ack. STEP 1: core/sdis/transfer.py:"
       " FRAME_PUSH = 'sdis_push'; push(session, files) (staff side): send {t: 'sdis_push', files: [{name,"
       " size, sha256}]}, then each file with session.send_file, then read {t: 'sdis_ack', files: [...]}"
       " and return the acked names; handle_push(session, app_dir) (admin side): refuse (send {t:"
       " 'sdis_ack', files: []}) unless this PC is the admin PC (sync_admin.is_admin_pc(app_dir)); else"
       " recv_file each into core.sdis.paths.data_dir()/'corpus'/<peer device id>/<name> (session has the"
       " peer device id), check the SHA-256 (recv_file returns it), ack only the files whose hash matches."
       " Never log contents. STEP 2: sync_office.dispatch_session: add `elif t == 'sdis_push':` ->"
       " core.sdis.transfer.handle_push (lazy import). STEP 3: staff side trigger: find where the app"
       " connects to the admin PC for sync (grep sync_engine.py for how it opens a client Session to a"
       " peer, and main.py for the sync engine's start and its timer); after each successful sync round,"
       " or at most every 15 minutes, in a background thread: list finished sdis_capture files (not"
       " today's open file), push them, and delete exactly the acked ones. On the admin PC itself the"
       " recorder's folder is read by mine() directly (no push). STEP 4: tests"
       " (tests/test_sdis_transfer.py): a loopback mutual-TLS session the way tests/test_sync_transport*.py"
       " builds one; push two files -> both acked and stored under corpus/<device>; a corrupted file ->"
       " not acked and not deleted on the staff side; a non-admin receiver acks nothing. Hands-on check:"
       " `check-add W4-2 --text \"Two real office PCs: a staff PC's sdis_capture files arrive on the admin"
       " PC and are deleted on the staff PC only after arriving\"`."),

    wp("W4-3", 4, "opus", "M", ["W3-3"], "Part O: mining in its own process (no CPU cap)",
       "Blueprint Part O. Owner decision 2026-10-04: mining runs only on the admin PC, so it is NOT CPU-capped"
       " - no Job Object, no priority change; it runs as fast as the PC allows. It still runs in a separate"
       " process so the app stays responsive and Cancel is instant. STEP 1: core/sdis/mine_process.py:"
       " run(argv) parses --captures, --state, --rebuild; runs mine() with progress printing one JSON line"
       " per step to stdout ({\"done\": n, \"total\": t, \"page\": link}, flushed) and a final"
       " {\"result\": \"ok\", ...summary} or {\"result\": \"error\", \"message\": ...}; exit code 0/1. STEP 2:"
       " main.py: at the very top, right after `import sys` and BEFORE any PySide6, database or app import,"
       " add: if '--sdis-mine' in sys.argv: from core.sdis.mine_process import run; sys.exit(run(sys.argv))."
       " Check the PyInstaller spec in build_tools/ (grep hiddenimports) and add core.sdis.mine_process if"
       " modules are listed by hand; do NOT build an installer. STEP 3: core/sdis/miner_client.py:"
       " MinerClient.start(captures, state) runs [sys.executable, '--sdis-mine', ...] when frozen"
       " (getattr(sys, 'frozen', False)) else [sys.executable, <repo>/main.py, '--sdis-mine', ...], with"
       " CREATE_NO_WINDOW; a reader thread parses the JSON lines and calls on_progress / on_done;"
       " cancel() terminates the process (the state on disk is safe: it is saved after every client)."
       " Tests (tests/test_sdis_mine_process.py): run(argv) on the fixtures in a tmp folder prints progress"
       " lines and a final ok; a bad --captures folder gives a final error line and exit 1; MinerClient end"
       " to end against the fixtures, and cancel() mid-run leaves a loadable state. Hands-on check:"
       " `check-add W4-3 --text \"Find datapoints on the admin PC: the loading dialog shows progress, Sera"
       " stays responsive behind it, Cancel stops mining at once and the next run continues\"`."),

    wp("W4-4", 4, "opus", "L", ["W3-3"], "Part Q: registration on every PC (synced tables)",
       "Blueprint Part Q and rule 8. D7, D15 and D6 are taken (user, 2026-10-04): registered on every PC only after the user's OK;"
       " no tracker column is added automatically; labels, rejections and container moves live in"
       " synced office tables. STEP 1: tables sdis_fields (gid, name, portal, section, spec_json, label,"
       " status, created_by, updated_at) and sdis_decisions (gid, signature, decision, label, updated_at):"
       " create them where the office tables are created (sera_db/schema.py; follow tracker_dump) and"
       " register them for replication in sync_schema.py with _register(TableSpec(...)) exactly like"
       " tracker_dump; a sera_db mixin module sera_db/sdis.py with add/rename/retire/list functions (follow"
       " sera_db/tracker_dump.py and how database.py composes mixins). Run tests/test_sync_schema.py."
       " STEP 2: core/sdis/register.py: draft_spec(datapoint) uses core.sgt_i.miner.draft_field(label,"
       " typ, shapes, field, section, portal) - shapes = {value shape: count} where a value's shape maps"
       " letters to 'A' and digits to '9' per character (read miner.fill_shape / value_regex to match"
       " their shape format exactly); the spec's section comes from the field's container (Part S.3):"
       " 'profile' only for a Profile builder field; dataset and Others fields are written so that SGT"
       " does NOT treat them as profile (they latch nothing; W4-7 consumes them through the containers"
       " file) - until W4-7 lands, register only Profile builder fields and say so in the hand-off."
       " write_fields_file(rows) writes the active rows, with the user's label, in sgt_fields.json format"
       " to <Sera data dir>/sdis_fields.json atomically. STEP 3: core/sgt/sgt_specs.py: SpecStore's default"
       " paths become [BUILTIN_FIELDS_PATH, override_path(), sdis_fields_path()] (a missing file is fine -"
       " _stamps already handles it); load_registry's default list too. STEP 4: rewrite the file at"
       " start-up and whenever the tables change (find the hook main.py runs after sync applies remote"
       " changes; also call it after a local add/rename). Renaming changes only the label; the spec's"
       " field name stays. Tests: tests/test_sdis_register.py (draft a spec from a fake datapoint and"
       " load it through load_registry; rename keeps the field; empty table -> no file or empty file);"
       f" `{T} tests/test_sgt_*.py tests/test_sync_schema.py` and `{PY} tools/sgt_replay.py diff` with an"
       " empty table -> no change. Note in the hand-off that main has uncommitted edits to sync_schema.py"
       " and sera_db/schema.py from other work, so the merge must be checked there."),

    wp("W4-5", 4, "sonnet", "L", ["W3-5", "W4-3", "W4-6"], "Part L: the Distill dialog + loading dialog + containers",
       "Blueprint Part L and Part O (UI). BUILD TO THE DESIGN: docs/sdis/distill-dialog-mockup.html,"
       " frames A-E (open it in a browser; layout, columns, chips, colours, wording and states are the"
       " spec; Qt widgets may differ in detail, never in content or order). STEP 1: ui/windows/tracker_dump_window.py: in"
       " _show_preferences_menu (the 'Tools  ▾' button) add 'Distill…' (icon mdi.flask-outline). On a"
       " PC that is not the admin PC (db.is_admin_pc()) show a QMessageBox 'Sera Distill runs on the"
       " admin PC only.' and stop. STEP 2: ui/dialogs/sdis_dialog.py, a non-modal QDialog, readable and"
       " calm (NOT the SGT lab's dense screen; reuse the colours of tracker_dump_window's stylesheet):"
       " top bar = 'Find datapoints' button + 'Last run: <time>' + filters (search box, Relevance >= x%,"
       " page, browser, state); main area = QTreeWidget, one top-level row per Datapoint (columns: Label,"
       " Relevance %, Sure %, Type, Found on (n pages)), its child rows = the pages it was found on"
       " (collapsible arrow, R5); the Label cell is editable by double-click (R6) and the edit is saved at"
       " once (sdis_decisions / sdis_fields via the W4-4 functions) and NEVER overwritten by a later run;"
       " a 'Register' button for the selected datapoint (asks 'Capture <label> on every PC?' then W4-4's"
       " register); a second tab 'Please check' listing variable_alignment items with Keep / Reject"
       " buttons (Reject is saved and sent to the next mining run); every number shown is a percentage"
       " (R7). STEP 2b: the containers (blueprint Part L and Part S): a side panel with the Profile"
       " builder of each registered portal, the Dataset containers (create / rename / delete; each lists its fields and n)"
       " and one Others per registered portal (Part T, core.sdis.portals); each datapoint row shows"
       " its suggested container (W3-5) and an 'Add to…' action that registers it (D7) as a field of"
       " sdis_mcl through the W4-6 functions (container edits go through core.sdis.config's helpers; per"
       " field in a container the user can mark period / form, tick optional and set proves <level>; a"
       " levels editor (file-wide and per container) writes levels / level_map; a"
       " refused edit shows the check's reason; Export / Import buttons for the containers file); the label editor offers existing sdis_mcl fields first"
       " (QCompleter). STEP 3: the loading dialog: an APPLICATION-MODAL QDialog (locks the app, not Windows) with a"
       " progress bar, 'Working on <done> of <total> - <page link>' and a Cancel button, driven by"
       " core/sdis/miner_client.MinerClient through Qt signals (never block the UI thread); on done it"
       " reloads the results from the saved state. Opening the dialog never starts mining. Tests"
       " (tests/test_sdis_dialog.py, QT_QPA_PLATFORM=offscreen like tests/test_sgt_i_lab.py): the dialog"
       " builds from a fake state with 3 datapoints; a datapoint row has its page children; editing a"
       " label calls the save function; the non-admin path shows the message (monkeypatch"
       " QMessageBox). Hands-on check: `check-add W4-5 --text \"Admin PC: Tracker dump -> Tools ->"
       " Distill...: Find datapoints shows the loading dialog and locks the app; Cancel works; rename a"
       " label, register a datapoint, and see it captured on another PC after sync\"`."),

    wp("W4-6", 4, "opus", "L", ["W4-4", "W1-8"], "Parts U + S.3: sdis_mcl, the containers file (sync + checks)",
       "Blueprint Parts U, S.3 (the JSON shape, the levels syntax, the exceptions table and the load"
       " checks are exact) and Q. D19 and D23 are taken (user, 2026-10-04): ONE PROFILE BUILDER PER"
       " REGISTERED PORTAL ('profile' is {portal: [fields]}), and sdis_mcl is separate from mcl_columns."
       " Completion levels are NOT in code: the built-in file has none, and the code must not assume any"
       " level name or threshold. STEP 1: synced office tables, created and registered exactly like"
       " W4-4's sdis_fields: sdis_mcl (gid, name, label, value_type, class, portal, status, created_by,"
       " updated_at) and sdis_config (gid, name = 'containers', doc_json, version, updated_by,"
       " updated_at: ONE row holding the whole containers document). sdis_fields gains mcl_gid."
       " sera_db/sdis.py: add/rename/retire/list for sdis_mcl (renaming a field renames its label in"
       " every sdis_fields row, R6); get/put for the containers document (put runs"
       " core.sdis.config.check first and refuses a failing document; version + 1). STEP 2:"
       " core/sdis/config.py (from W1-8): implement the remaining checks of S.3 (levels and when;"
       " level_map; profile and others per registered portal; containers with form_field /"
       " period_field / fields / exceptions.optional / exceptions.proves / their own levels and"
       " level_map / examples; class_exceptions) and level_for(container, captured_fields, doc) used by"
       " the examples check: n = fields minus optional; k = captured counted fields; levels = the"
       " container's own, else the file's; a `when` holds if its `captured` holds (a number: k >= it;"
       " 'p%': k >= ceil(p/100 * n); 'all': k == n) and its `fields` are all captured; the result is"
       " the highest level whose when holds, raised to every proves hit; no levels -> None (the caller"
       " shows 'k of n' only). Helpers that edit the document (add_container, rename_container,"
       " delete_container, add_field, remove_field, mark_key, set_exception, set_levels, move_field) each"
       " return a new document that passes check(). STEP 3: every PC writes the sdis_config row to"
       " <Sera data dir>/sdis_containers.json atomically whenever it changes (the same hook W4-4 uses for"
       " sdis_fields.json) and at start-up; export(path) / import(path) for the admin (import = check +"
       " put). STEP 4: core/sdis/register.py registers a datapoint as a field: sdis_mcl row (new or"
       " existing) + its spec in sdis_fields; the container it goes in is a config edit, never a spec"
       " change. core/sdis/classes.py suggest() honours class_exceptions. Tests"
       " (tests/test_sdis_containers.py): the blueprint's example document passes and its examples give"
       " their levels (n = 3 there: filing_date is optional; arn proves Complete); a document with no"
       " levels passes and level_for gives None; a container's own levels replace the file's; each load"
       " check refuses its own broken document and the previous version stays; one field registered on"
       " two pages = two specs, one field; rename reaches both; moving a field between containers leaves"
       " sdis_fields.json byte-identical; empty tables -> no file change. Run"
       f" `{T} tests/test_sgt_*.py tests/test_sync_schema.py` and `{PY} tools/sgt_replay.py diff` -> no"
       " change."),

    wp("W4-7", 4, "opus", "L", ["W4-6"], "Part S.2 in SGT: container instances, completion, Others values",
       "Blueprint Part S.2, S.3 and rule 8. Taken (user, 2026-10-04): D17 instance key = (client, form,"
       " period), form = the container's name unless form_field is set, period = period_field; D18 is"
       " superseded: levels and their ladder mapping come ONLY from the containers file (levels,"
       " level_map), never from code; D19 one Profile builder per registered portal; D20 Others: the"
       " latest value wins and the history is kept; D22 one instance per page and key (no list pages"
       " yet). STEP 1: core/sgt/sgt_containers.py (pure, no UIA): load the containers document through"
       " core.sdis.config (a refused file -> the last good one; none -> no containers);"
       " Instance(container, client, form, period, values {field: value}, evidence, level) whose level is"
       " core.sdis.config.level_for(...) and only promotes; apply(instance, field, value). STEP 2:"
       " core/sgt/sgt_shadow.py: for each container, build instances the way current_dataset is built (a"
       " value shown once on a page belongs to the instance being worked on; a new period starts a new"
       " instance; values seen before the period wait in the session); write each instance to the tracker"
       " dump under core/dataset_key.compute_dataset_key with its status = level_map[level] ('k of n'"
       " and the proves hit, if any, kept as evidence); with no level (no levels defined) the status is"
       " SGT's existing minimum for a keyed dataset (Draft); never lower a status; never touch the"
       " built-in GST/ITR datasets. Others and Profile builder values: blueprint S.4 exactly - SGT puts"
       " them in its rows' payload JSON under 'sdis' ({portal, portal_profile, others, at}); a session"
       " with such values but no dataset row writes ONE carrier row per (client, portal), capture"
       " method 'SGT_sdis_info', no form/period, which every tracker view, counter and status resolver"
       " ignores (grep tracker_dump_window.py, sera_db/tracker_dump.py and the status resolver);"
       " sera_db/srpf.py _update_srpf_container folds 'sdis' into client_raw_containers.raw_aggregates"
       " ({portal: {field: {value, updated_at, history}}}, latest at wins, D20) and portal_profiles"
       " ({portal: {field: value}}, latching); re_resolve_all_tracker_dumps() must rebuild the same"
       " values (test it). Show them in the client detail window and the Tracker dump container view,"
       " per portal, with sdis_mcl labels. Profile builder fields are also ordinary profile specs of"
       " their portal. STEP 3: a changed document recomputes instances; none moves"
       " down. Tests (tests/test_sgt_containers.py) with fixture documents written in the test: a"
       " count-based levels list and a fields-based one; optional fields not counted; a proves field"
       " lifts and a later count never lowers; a container's levels/level_map replace the file's; no"
       " levels -> 'k of n' and Draft; a field captured on two pages fills one slot; a new period opens a"
       " new instance; a changed document never lowers a level; Others values reach raw_aggregates with"
       " history and survive re_resolve_all_tracker_dumps(); a carrier row is not counted or listed"
       " as a dataset. Run"
       f" `{T} tests/test_sgt_*.py` and `{PY} tools/sgt_replay.py diff` with no containers -> no change."
       " Hands-on check: `check-add W4-7 --text \"Write levels and a 4-field dataset container into the"
       " containers file; on a portal, capture its fields one by one and see the tracker row climb the"
       " levels you wrote\"`."),


    wp("W5-R", 5, "opus", "M", ["W4-2", "W4-5", "W4-7", "W3-4"], "Final review and merge-readiness note",
       "Review the whole branch against blueprint sections 0 and 9 and every Part. Run all"
       f" tests/test_sdis_*.py, tests/test_class_diff_align.py, tests/test_sgt_*.py, tests/test_sync_*.py"
       f" and `{PY} tools/sgt_replay.py diff` (no change); run the regression runner and compare with"
       " docs/sdis/sdis-regress-baseline.txt, explaining every difference. grep core/sdis for any print or"
       " log of a text/value (only counts allowed). Fix defects with tests. Write the merge-readiness note"
       " in section 11 of the blueprint (what is built, what changed for SGT, the files on main that will"
       " conflict - sync_schema.py, sera_db/schema.py, main.py, unified_settings_dialog.py,"
       " tracker_dump_window.py have uncommitted edits on main - and the hands-on checks to run before"
       " merging).", kind="review"),
]


def main() -> None:
    base = json.loads(AUTOFILL.read_text(encoding="utf-8"))
    plan = {
        "about": ("Sera Distill (SDIS) work packages (blueprint docs/sdis/sdis-blueprint.md). Fixed data:"
                  " re-plan by editing docs/sdis/make_plan.py and running it. Live status is in"
                  " sdis-status.csv, written only by tools/sdis.py."),
        "deadline": "2026-10-06T01:30:00+05:30",
        "models": {k: v for k, v in base["models"].items() if v["runner"] == "claude" or k == "gemini-flash"},
        "tiers": {"_note": ("Owner decision 2026-10-04: twelve engine-only WPs (no SGT, sync, DB or UI) go to"
                            " Gemini first to save Claude tokens; Claude Sonnet takes over on Gemini's quota/sign-in"
                            " or from the second attempt (cli.non_claude_attempts). Everything else Claude only."),
                  "sonnet": ["sonnet"], "haiku": ["haiku"], "opus": ["opus"],
                  "gemini_first": ["gemini-flash", "sonnet"]},
        "runners": {"claude": base["runners"]["claude"],
                    "antigravity": dict(base["runners"]["antigravity"], enabled=True, _note=(
                        "Owner decision 2026-10-04: unrestricted (--dangerously-skip-permissions). Measured with"
                        " agy 1.2.14: restricted print mode refuses every command and settings.json allow-rules"
                        " match only the exact command line, so a restricted worker cannot run the tests. The"
                        " rules Gemini follows are GEMINI.md's allow/blocklist and this runner prompt; git push is"
                        " refused by the repository's pre-push hook (SGT_OVERHAUL_WORKER)."))},
        "cli": dict(base["cli"], non_claude_attempts=1),
        "wps": WPS,
    }
    ids = {w["wp"] for w in WPS}
    for w in WPS:
        assert all(d in ids for d in w["deps"]), w["wp"]
    (HERE / "sdis-plan.json").write_text(json.dumps(plan, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{len(WPS)} WPs written")


if __name__ == "__main__":
    main()
